name: "Parse vacancies, update GitHub pages page"

on:
#  push:
#    branches: [ master ]
   workflow_dispatch:
     inputs:
       vacancy_age:
         description: "vacancy age"
         required: true
         default: "30"
       hh_search_text:
         description: "HH search string"
         required: true
         default: "devops"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Clean
      run: go get -d # && gh --help

    - name: Check env vars
      run: printenv | grep INPUT_

    - name: Run
      run: go run hh.go

    - name: Push to Pages
      env:
        PAGES_REPO_DEPLOY_KEY: ${{ secrets.PAGES_REPO_DEPLOY_KEY }}
      run: |
        echo "${PAGES_REPO_DEPLOY_KEY}" > .key && \
        chmod 0700 .key && \
        GIT_SSH_COMMAND="ssh -i .key" git clone git@github.com:iLychevAD/iLychevAD.github.io.git pages && \
        cd pages && \
        git checkout hh || git checkout -b hh && \
        mkdir -p hh && \
        cp ../index.html hh/index.html && \
        git add hh/index.html && \
        git config user.email "github-actions@example.com" && \
        git config user.name "GitHub Actions" && \
        git commit -m "`date`" && \
        GIT_SSH_COMMAND="ssh -i ../.key" git push -u origin hh
