name: Go

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Clean
      run: go mod vendor

    - name: Run
      run: go run hh.go
    - name: Debug
      run: pwd; ls -lah; git status
